apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pvc
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /pvstorage1
    server: 10.84.60.170
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-storage-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: efs-pvc
  resources:
    requests:
      storage: 1T
